version: '3'

services:
  
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '8080:15672'

  server:
    image: 'alexkcode/webhook-flask-listener:latest'
    build: server
    volumes:
      - ./server:/app
    ports:
      - '5000:5000'